---
- name: Enable passwordless sudo for sysadmin
  hosts: SuperComputer
  become: true
  tasks:
    - name: Allow sysadmin to run sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/sysadmin
        create: yes
        line: "sysadmin ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

